from .mask import Mask

BATTLE_LOBBY_MATCHING_PREFIX = Mask("battle_lobby_matching_prefix")
BATTLE_LOBBY_MATCHED = Mask("battle_lobby_matched")
BATTLE_INTRO_TITLE = Mask("battle_intro_title")
BATTLE_RESULT_LOSE = Mask("battle_result_lose")
BATTLE_RESULT_WIN = Mask("battle_result_win")
BATTLE_MAP_ICON = Mask("battle_map_icon")
BATTLE_RESULT_MEDAL_HEADER = Mask("battle_result_medal_header")
BATTLE_INGAME_TIME_COLON = Mask("battle_ingame_time_colon")
BATTLE_INGAME_MUSIC_HEADER = Mask("battle_ingame_music_header")
BATTLE_RESULT_SCOREBOARD_ABUTTON = Mask("battle_result_scoreboard_abutton")
BATTLE_RESULT_SCOREBOARD_WINP = Mask("battle_result_scoreboard_winp")
BATTLE_INTRO_RULE_NAWABARI = Mask("battle_intro_rule_nawabari")
BATTLE_INTRO_RULE_AREA = Mask("battle_intro_rule_area")
BATTLE_INTRO_RULE_YAGURA = Mask("battle_intro_rule_yagura")
BATTLE_INTRO_RULE_HOKO = Mask("battle_intro_rule_hoko")
BATTLE_INTRO_RULE_ASARI = Mask("battle_intro_rule_asari")
ERROR_SCHEDULE_REFRESH = Mask("error_schedule_refresh")
