from .mask import Mask

SHARAED_LOBBY_MATCHING_PREFIX = Mask("shared_lobby_matching_prefix")
SHARED_RESULT_PLEASE_WAIT = Mask("shared_result_please_wait")

BATTLE_LOBBY_MATCHED = Mask("battle_lobby_matched")
BATTLE_INTRO_TITLE = Mask("battle_intro_title")
BATTLE_INTRO_TITLE_TRICOLOR = Mask("battle_intro_title_tricolor")
BATTLE_RESULT_LOSE = Mask("battle_result_lose")
BATTLE_RESULT_WIN = Mask("battle_result_win")
BATTLE_MAP_ICON = Mask("battle_map_icon")
BATTLE_RESULT_MEDAL_HEADER = Mask("battle_result_medal_header")
BATTLE_INGAME_TIME_COLON = Mask("battle_ingame_time_colon")
BATTLE_INGAME_TIME_COLON_TRICOLOR = Mask("battle_ingame_time_colon_tricolor")
BATTLE_INGAME_MUSIC_HEADER = Mask("battle_ingame_music_header")
BATTLE_RESULT_SCOREBOARD_ABUTTON = Mask("battle_result_scoreboard_abutton")
BATTLE_RESULT_SCOREBOARD_WINP = Mask("battle_result_scoreboard_winp")
BATTLE_RESULT_SCOREBOARD_WINP_TRICOLOR = Mask("battle_result_scoreboard_winp_tricolor")
BATTLE_RESULT_SCOREBOARD_NO_GAME = Mask("battle_result_scoreboard_no_game")
BATTLE_INTRO_RULE_NAWABARI = Mask("battle_intro_rule_nawabari")
BATTLE_INTRO_RULE_AREA = Mask("battle_intro_rule_area")
BATTLE_INTRO_RULE_YAGURA = Mask("battle_intro_rule_yagura")
BATTLE_INTRO_RULE_HOKO = Mask("battle_intro_rule_hoko")
BATTLE_INTRO_RULE_ASARI = Mask("battle_intro_rule_asari")
BATTLE_INTRO_RULE_TRICOLOR_GUARD = Mask("battle_intro_rule_tricolor_guard")
BATTLE_INTRO_RULE_TRICOLOR_ATTACK = Mask("battle_intro_rule_tricolor_attack")
BATTLE_RESULT_BANKARA_CHALLENGE_FINISH_TITLE = Mask("battle_result_bankara_challenge_finish_title")
BATTLE_RESULT_BANKARA_CHALLENGE_FINISH_ABUTTON = Mask("battle_result_bankara_challenge_finish_abutton")

SALMON_LOBBY_MATCHED = Mask("salmon_lobby_matched")
SALMON_INGAME_WAVE_HEADER = Mask("salmon_ingame_wave_header")
SALMON_RESULT_PLAYERLIST_1ST_DEAD_COUNT = Mask("salmon_result_playerlist_1st_dead_count")
SALMON_RESULT_POINT_DESC_HEADER = Mask("salmon_result_point_desc_header")

ERROR_SCHEDULE_REFRESH = Mask("error_schedule_refresh")
ERROR_SERVER_MAINTENANCE_SOON = Mask("error_server_maintenance_soon")
ERROR_NO_GAME_BY_DISCONNECT = Mask("error_no_game_by_disconnect")